### ISSUE TITLE
Notifies services with unsupported action

### ISSUE THREAD

**Issue by veetow** [StackStorm/chef-openstack-mistral#5]
In the default recipe, the mistral.conf template resource notifies three services to reload:
https://github.com/StackStorm/chef-openstack-mistral/blob/master/recipes/default.rb#L51-L53

However, those services do not support reload as an action:
https://github.com/StackStorm/chef-openstack-mistral/blob/master/recipes/default.rb#L18
https://github.com/StackStorm/chef-openstack-mistral/blob/master/recipes/default.rb#L23
https://github.com/StackStorm/chef-openstack-mistral/blob/master/recipes/default.rb#L28

I believe the notification should be for the `:restart` action, as that is what the service seems to support:

`Failed to reload mistral-server.service: Job type reload is not applicable for unit mistral-server.service.`

**Comment by arm4b** [comment]
Digging deeper, seems there is more inconsistency like this: 
- https://github.com/StackStorm/st2-packages/blob/21de784087d3e5af04cde75e50f56cd58a5229cb/packages/st2mistral/rpm/mistral.init#L49-L51
- https://github.com/StackStorm/st2-packages/blob/21de784087d3e5af04cde75e50f56cd58a5229cb/packages/st2mistral/debian/mistral-api.init#L109-L119

Having `reload` would be nice, but it's not implemented in existing `init` scripts.
Apart of that, @m4dcoder do you know whether mistral handles `SIGHUP` signals internally to reload `mistral.conf` without process restart?

**Comment by arm4b** [comment]
@veetow So yeah, you're right.

PR to use `:restart` instead of `:reload` is welcomed!

**Comment by veetow** [comment]
@armab, in my local testing, I hit some other issues with `:restart` instead of `:reload`.  I need to test a bit more to be sure it's not something in my environment before I feel comfortable issuing the PR.
